---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-longhorn-volv-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pihole
  name: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pihole
    spec:
      containers:
        - image: pihole/pihole
          name: pihole
          resources: {}
          env:
            - name: TZ
              value: "America/New_York"
            - name: WEBPASSWORD
              value: "initial"
            - name: DNSMASQ_LISTENING
              value: "all"
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pihole
  name: pihole-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
  selector:
    app: pihole
  type: LoadBalancer
status:
  loadBalancer: {}
