---
- name: installs helm repo and its repository on ubuntu
  hosts: helm
  become: true
  tasks:
    - name: install needed dependencies via apt
      ansible.builtin.apt:
        pkg:
          - curl
          - apt-transport-https

    - name: install repository and key (not idempotent)
      ansible.builtin.shell: |
        curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        apt update

    - name: install helm kubernetes package manager
      ansible.builtin.apt:
        name: helm
