---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: media
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jellyfin
  name: jellyfin
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jellyfin
    spec:
      containers:
      - image: jellyfin/jellyfin:latest
        name: jellyfin
        resources: {}
        volumeMounts:
        - mountPath: /media
          name: media-vol
      volumes:
      - name: media-vol
        nfs:
          server: 192.168.0.106
          path: /exports/nfs_share/media1
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jellyfin
  name: jellyfin
  namespace: media
spec:
  ports:
  - port: 8096
    protocol: TCP
    targetPort: 8096
    nodePort: 32001
  selector:
    app: jellyfin
  type: NodePort
status:
  loadBalancer: {}
