FROM debian:bookworm

# tell systemd, its running in a container
ENV container=docker 
# use bash for shell, and fail on first error
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    systemd systemd-sysv dbus sudo \
    python3 python3-apt ca-certificates \
    iproute2 iputils-ping && \
    # mask useless services in containers \
    ln -sf /dev/null /etc/systemd/system/getty.target && \
    ln -sf /dev/null /etc/systemd/systemd-logind.service && \
    ln -sf /dev/null /etc/systemd/systemd-udevd.service && \
    ln -sf /dev/null /etc/systemd/systemd-udev-trigger.service && \
    ## clean temp fiels
    apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 80
EXPOSE 22

STOPSIGNAL SIGRTMIN+3
VOLUME ["/sys/fs/cgroup"]

# Boot systemd
CMD ["/sbin/init"]
