---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: tovuti
spec: {}
status: {}
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: tovuti
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tovuti
  name: tovuti
  namespace: tovuti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tovuti
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tovuti
    spec:
      containers:
      - image: gitea.kwerezigua.org/iskm/tovuti:latest
        name: tovuti
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tovuti
  name: tovuti
  namespace: tovuti
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tovuti
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: tovuti
  namespace: tovuti
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: www.kwerezigua.org
    http:
      paths:
      - backend:
          service:
            name: tovuti
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - www.kwerezigua.org
    secretName: kwerezigua-ca-secret
status:
  loadBalancer: {}

