---
- name: sets up the control node
  hosts: localhost
  vars_files:
    - ../vars/secrets.yml
  tasks:
    - name: create the ansible control user
      user:
        name: ansible
        generate_ssh_key: true
    - name: Create the password for the control user
      shell:
        cmd: echo {{ become_password }} | passwd --stdin ansible
      when: ansible_os_family == 'RedHat'
      #when: ansible_facts['ansible_os_family'] == 'RedHat'
    - name: install chpasswd on debian family os
      shell:
        cmd: echo ansible:{{ become_password  }} | chpasswd
      when: ansible_os_family == 'Debian'
